/**
 * Department Responsibility Framework.
 * For every department / process: role, responsibility, daily activities, documents,
 * reports, KPIs, coordination, common problems and problem-solving method.
 */
export const FRAMEWORK = [
  {
    department: 'Admin', modules: ['users', 'roles', 'settings', 'audit', 'jobs'],
    role: 'ERP Administrator / General Manager',
    responsibility: 'Owns system configuration, user access, workflow rules and final job closure. Guarantees data integrity and controlled overrides.',
    daily: ['Review dashboard & delayed jobs', 'Approve overrides with reasons', 'Close jobs that are READY TO CLOSE', 'Review audit trail for unusual changes', 'Manage users, roles and permissions'],
    documents: ['User access matrix', 'Workflow configuration', 'Job closure report'],
    reports: ['Job Closure Report', 'Order Status Report', 'Profit Report', 'Audit Trail export'],
    kpis: ['Jobs closed on time', 'Overrides per month', 'Open jobs ageing', 'System adoption (active users)'],
    coordination: ['All departments'],
    problems: ['Users sharing passwords', 'Status skipped without justification', 'Jobs left open after payment'],
    solutions: ['Enforce individual accounts & forced password change', 'Allow skips only via override with mandatory reason (audited)', 'Use Ready-to-Close list weekly and close in bulk'],
  },
  {
    department: 'Head Office Merchandising', modules: ['enquiry', 'quotation', 'orders', 'sample'],
    role: 'Senior Merchandiser / Account Manager',
    responsibility: 'Buyer relationship, enquiry handling, quotation, order confirmation, buyer approvals and shipment follow-up.',
    daily: ['Respond to buyer enquiries', 'Prepare / revise quotations from approved costing', 'Confirm orders and generate Job No', 'Chase buyer approvals', 'Update buyer on production & shipment'],
    documents: ['Buyer PO', 'Tech pack', 'Quotation PDF', 'Approval comments', 'Order confirmation'],
    reports: ['Buyer Order Report', 'Quotation Report', 'Order Status Report', 'Sample Status Report'],
    kpis: ['Order conversion %', 'Quotation turnaround (days)', 'On-time approval %', 'Order value booked'],
    coordination: ['Costing Factory', 'Factory Merchandising', 'Shipment / Documentation', 'Accounts & Finance'],
    problems: ['Late buyer comments', 'Price pressure below cost', 'PO changes after confirmation'],
    solutions: ['Escalate approvals via T&A delay alerts', 'Use costing margin view before re-quoting; revise quotation with version control', 'Edit order – the system shows impacted processes and re-calculates early-stage requirements'],
  },
  {
    department: 'Costing Factory', modules: ['costing'],
    role: 'Costing Executive / Industrial Engineer',
    responsibility: 'Builds accurate cost sheets (fabric, trims, CM, overheads, commercial costs) and target margins.',
    daily: ['Prepare cost sheets for new enquiries', 'Update fabric & trim rates', 'Validate SAM and CM', 'Review margin with management'],
    documents: ['Cost sheet', 'Consumption sheet', 'Rate references'],
    reports: ['Costing Report', 'Margin analysis'],
    kpis: ['Costing accuracy (expected vs actual cost variance)', 'Average profit %', 'Turnaround time'],
    coordination: ['Head Office Merchandising', 'Fabric Department', 'Production', 'Accounts & Finance'],
    problems: ['Under-estimated consumption', 'Outdated rates', 'Missing hidden costs (testing, freight)'],
    solutions: ['Compare with actual cutting consumption from Cutting module', 'Maintain rate masters', 'Use full component list incl. testing, freight, finance cost'],
  },
  {
    department: 'Factory Merchandising', modules: ['tna', 'ppMeeting', 'trimBooking', 'sample'],
    role: 'Factory Merchandiser',
    responsibility: 'Executes the order inside the factory: T&A, PP meeting, trims, sampling and production follow-up.',
    daily: ['Update T&A actual dates', 'Book & chase trims', 'Submit samples & record comments', 'Run PP meeting and close action items', 'Follow up production vs plan'],
    documents: ['T&A calendar', 'Trim card', 'PP meeting minutes', 'Sample requisition'],
    reports: ['T&A Report', 'Trim Report', 'Sample Status Report'],
    kpis: ['T&A on-time %', 'Trim in-house on time', 'Sample right-first-time %'],
    coordination: ['Head Office Merchandising', 'Fabric Department', 'Production', 'Quality'],
    problems: ['Trim shortages at sewing', 'Samples rejected repeatedly', 'PP meeting held late'],
    solutions: ['Book trims with wastage %, monitor shortage alerts', 'Record buyer comments per revision; review before resubmission', 'PP meeting auto-scheduled at order confirmation – track in T&A'],
  },
  {
    department: 'Fabric Department', modules: ['yarnReceipt', 'knitting', 'fabricProcess', 'fabricBooking'],
    role: 'Fabric Manager / Fabric Store Keeper',
    responsibility: 'Yarn purchase, knitting, grey fabric, processing (dyeing, compacting…), finished fabric receipt, issue to cutting and fabric job closure.',
    daily: ['Book fabric against requirement', 'Receive & inspect rolls (4-point)', 'Approve and issue to cutting', 'Update balances', 'Close fabric jobs that are READY TO CLOSE'],
    documents: ['Fabric PO', 'GRN', 'Inspection report', 'Issue note', 'Fabric closure note'],
    reports: ['Yarn Stock', 'Knitting Report', 'Grey Fabric Stock', 'Processing Report', 'Finished Fabric Stock', 'Fabric Booking Report', 'Fabric Balance Report'],
    kpis: ['Fabric booking %', 'Fabric in-house %', 'Fabric shortage qty', 'Fabric wastage %'],
    coordination: ['Factory Merchandising', 'Cutting', 'Accounts & Finance', 'Quality'],
    problems: ['Shortage due to shrinkage / GSM variation', 'Late mill delivery', 'Excess left-over fabric'],
    solutions: ['Include shrinkage, relaxation, dyeing & process loss in requirement', 'Delivery date alerts and supplier follow-up', 'Close with "READY TO CLOSE / EXCESS BALANCE" and transfer leftovers'],
  },
  {
    department: 'Production', modules: ['productionPlan'],
    role: 'Production Manager / Planner',
    responsibility: 'Capacity planning, line allocation, daily targets and on-time output.',
    daily: ['Release plans after approvals & material readiness', 'Set line targets from SAM & efficiency', 'Review hourly output', 'Resolve bottlenecks'],
    documents: ['Production plan', 'Line layout', 'Operation bulletin'],
    reports: ['Production Report', 'Line efficiency report'],
    kpis: ['Daily target vs actual', 'Efficiency %', 'Line utilisation', 'WIP'],
    coordination: ['Cutting', 'Sewing', 'Finishing', 'Factory Merchandising', 'Quality'],
    problems: ['Low efficiency in first days (learning curve)', 'Material not ready', 'Absenteeism'],
    solutions: ['Plan learning curve targets', 'Release plan only when fabric/trim stages are green', 'Use HR attendance to rebalance lines'],
  },
  {
    department: 'Cutting', modules: ['cutting'],
    role: 'Cutting Master',
    responsibility: 'Markers, lay planning, cutting, numbering, bundling and fabric utilisation.',
    daily: ['Receive fabric issue', 'Plan lays & markers', 'Record cut quantities by ratio', 'Bundle & send to sewing', 'Report wastage'],
    documents: ['Cut plan', 'Lay report', 'Marker', 'Bundle ticket'],
    reports: ['Cutting Report'],
    kpis: ['Cutting wastage %', 'Marker efficiency %', 'Cut vs order qty'],
    coordination: ['Fabric Department', 'Sewing', 'Production'],
    problems: ['Over-cutting', 'Shade variation', 'High end-bit wastage'],
    solutions: ['System blocks cutting beyond order + tolerance without override', 'Shade-band & lot segregation', 'Optimise marker; compare actual vs costed consumption'],
  },
  {
    department: 'Sewing', modules: ['sewing'],
    role: 'Line Supervisor / Sewing Manager',
    responsibility: 'Line output, quality at source and efficiency.',
    daily: ['Record hourly production', 'Monitor DHU and alterations', 'Balance operators', 'Meet daily target'],
    documents: ['Hourly production board', 'End-line QC report'],
    reports: ['Sewing Report'],
    kpis: ['Efficiency %', 'DHU', 'Target achievement %', 'Line WIP'],
    coordination: ['Cutting', 'Finishing', 'Quality', 'Production'],
    problems: ['Bottleneck operations', 'High DHU', 'Input shortage'],
    solutions: ['Re-balance using operation SAM', 'Inline QC & operator training', 'Track cut vs sewn WIP daily'],
  },
  {
    department: 'Finishing', modules: ['finishing'],
    role: 'Finishing In-charge',
    responsibility: 'Thread trimming, ironing, checking, tagging and pass/reject decisions.',
    daily: ['Receive sewing output', 'Record pass, alteration, rework, rejection', 'Send passed goods to packing'],
    documents: ['Finishing report', 'Rejection report'],
    reports: ['Finishing Report'],
    kpis: ['Pass rate %', 'Rework %', 'Pending qty'],
    coordination: ['Sewing', 'Packing', 'Quality'],
    problems: ['Stains / measurement issues', 'Backlog before shipment'],
    solutions: ['Root-cause back to sewing line', 'Monitor pending qty vs ship date'],
  },
  {
    department: 'Packing', modules: ['packing'],
    role: 'Packing Supervisor',
    responsibility: 'Carton packing as per buyer ratio and packing list generation.',
    daily: ['Pack per assortment', 'Record carton ranges, weights and dimensions', 'Generate packing list'],
    documents: ['Packing list', 'Carton marks'],
    reports: ['Packing Report'],
    kpis: ['Packed vs order qty', 'Carton accuracy', 'CBM utilisation'],
    coordination: ['Finishing', 'Quality', 'Shipment / Documentation'],
    problems: ['Wrong ratio', 'Weight mismatch'],
    solutions: ['Ratio-based auto quantity per carton', 'Net/gross weights per carton captured & totalled automatically'],
  },
  {
    department: 'Quality', modules: ['inspection'],
    role: 'QA Manager / Inspector',
    responsibility: 'Inline and final inspections as per AQL; release goods for shipment.',
    daily: ['Inline audits', 'Final AQL inspections', 'Record defects (critical/major/minor)', 'Approve or reject lots'],
    documents: ['Inspection report', 'Inspection certificate'],
    reports: ['Quality Report'],
    kpis: ['AQL pass %', 'DHU', 'Rejection %', 'Alteration %'],
    coordination: ['Sewing', 'Finishing', 'Packing', 'Head Office Merchandising'],
    problems: ['Final inspection failure', 'Repeated defects'],
    solutions: ['Failure alerts trigger re-inspection flow', 'Defect trend analysis per line'],
  },
  {
    department: 'Shipment / Documentation', modules: ['shipment', 'documents'],
    role: 'Shipping & Documentation Executive',
    responsibility: 'Booking, stuffing, export clearance and buyer documentation.',
    daily: ['Book vessel/flight', 'Prepare commercial invoice & packing list', 'Track BL/AWB', 'Send documents to buyer/bank'],
    documents: ['Commercial invoice', 'Packing list', 'Certificate of origin', 'BL / AWB', 'Inspection certificate', 'Export declaration'],
    reports: ['Shipment Report'],
    kpis: ['On-time shipment %', 'Pending shipments', 'Document discrepancy count'],
    coordination: ['Packing', 'Quality', 'Accounts & Finance', 'Head Office Merchandising'],
    problems: ['Missed vessel cut-off', 'Document discrepancies'],
    solutions: ['Shipment due alerts 14 days ahead', 'Documents generated from the same job data – no re-typing'],
  },
  {
    department: 'Accounts & Finance', modules: ['invoice', 'payment', 'expense'],
    role: 'Accountant / Finance Manager',
    responsibility: 'Invoicing, receivables, payments, job costs and profitability.',
    daily: ['Raise invoices after shipment', 'Record payments', 'Follow up overdue receivables', 'Record job expenses', 'Review profit vs expected'],
    documents: ['Invoice', 'Payment advice', 'Bank realisation', 'Expense bills'],
    reports: ['Payment Report', 'Outstanding Report', 'Profit Report', 'Expense Report'],
    kpis: ['Receivable', 'Outstanding', 'Collection %', 'Payment delay', 'Actual profit %'],
    coordination: ['Shipment / Documentation', 'Head Office Merchandising', 'Admin'],
    problems: ['Over-payment entries', 'Unrecorded job expenses', 'Late collections'],
    solutions: ['System blocks payment above invoice outstanding', 'Expense entry per job & category', 'Payment-due notifications'],
  },
  {
    department: 'HR', modules: ['employee'],
    role: 'HR & Admin Officer',
    responsibility: 'Employee master, attendance summary, manpower availability for lines.',
    daily: ['Update attendance', 'Onboard / exit employees', 'Provide manpower to production'],
    documents: ['Employee records', 'Attendance sheet'],
    reports: ['Employee list', 'Attendance %'],
    kpis: ['Attendance %', 'Operator availability', 'Attrition'],
    coordination: ['Production', 'Sewing', 'Admin'],
    problems: ['Absenteeism affecting targets'],
    solutions: ['Share attendance daily with production planning'],
  },
  {
    department: 'Data Entry', modules: ['cutting', 'sewing', 'finishing'],
    role: 'Data Entry Operator',
    responsibility: 'Timely and accurate entry of production and movement data assigned by Admin.',
    daily: ['Enter cutting / sewing / finishing entries', 'Correct rejected entries'],
    documents: ['Production tickets'],
    reports: ['Daily entry summary'],
    kpis: ['Entry timeliness', 'Correction rate'],
    coordination: ['Cutting', 'Sewing', 'Finishing'],
    problems: ['Duplicate or late entries'],
    solutions: ['Quantity validations block impossible values; audit trail tracks every edit'],
  },
];
